name: Checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      # - run: deno lint
      - uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: cache-${{ hashFiles('import_map.json') }}
      - run: deno task check
      - run: deno test

